services:
  nginx:
    image: nginx
    ports:
      - "8002:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - menu
      - cart
      - order

  menu:
    build: ./menu-service
    container_name: menu-service

  cart:
    build: ./cart-service
    container_name: cart-service

  order:
    build: ./order-service
    container_name: order-service

